# ------- Start of Copy Me File Content -------------

version: '2'
services:
  test:
    title: 'Daily Smoke Test'
    image: 'automation:3.4'
    volumes:
      - './/test/schedule/v1'
    restart: always
#            min hour days mon year
    schdule: 15    1    *    *   *

  server-1:
    image: 'consul:1.0.6'
    volumes:
      - './/data/consul:/consul/data'
    ports:
      - '8500:8500'
    command: agent -server -bootstrap-expect=1 -ui -client 0.0.0.0
    environment:
      - 'CONSUL_LOCAL_CONFIG={"leave_on_terminate": true}'
    restart: always

# ------- End of Copy Me File Content -------------
